apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-kart-notification
  namespace: easy-kart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-kart-notification #This should be same label
  template:
    metadata:
      labels:
        app: easy-kart-notification #This should be same label
    spec:
      containers:
      - name: easy-kart-notification
        image: pdesaidocker/easy-kart-api-notification:{{imageTag}}
        resources:
          requests:
            memory: "128Mi"   # Minimum memory for the container to function
            cpu: "25m"       # Minimum CPU for the container to function
          limits:
            memory: "256Mi"   # Maximum memory that can be used
            cpu: "50m"       # Maximum CPU that can be used
        ports:
        - containerPort: 8080 #port defined in image dockerfile
        env:
        - name: ConnectionStrings__azservicebusconnstr
          valueFrom:
            secretKeyRef:
              name: easy-kart-secret  
              key: azservicebusconnstr
---
apiVersion: v1
kind: Service
metadata:
  name: easy-kart-notification-service
  namespace: easy-kart
spec:
  selector:
    app: easy-kart-notification #This should be same label
  ports:
    - protocol: TCP
      port: 80 #Other pods in the cluster can connect to this service on port 80
      targetPort: 8080 #port defined in image dockerfile
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easy-kart-notification-ingress
  namespace: easy-kart
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /notificationhub/$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
    ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: easy-kart.centralindia.cloudapp.azure.com
      http:
        paths:
          - path: /notificationhub(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: easy-kart-notification-service
                port:
                  number: 80
---